### PR TITLE
Jmm/1603 international addresses

### PR DESCRIPTION
**Pull request by JeanMarie-TTS**
## PR checklist: submitters

- [x]   Link to an issue if possible. If there’s no issue, describe what your branch does. Even if there is an issue, a brief description in the PR is still useful. #1603
- [ ]   List any special steps reviewers have to follow to test the PR. For example, adding a local environment variable, creating a local test file, etc.
- [ ]   For extra credit, submit a screen recording like [this one](https://github.com/GSA-TTS/FAC/pull/1821).
- [x]   Make sure you’ve merged `main` into your branch shortly before creating the PR. (You should also be merging `main` into your branch regularly during development.)
- [x]   Make sure that whatever feature you’re adding has tests that cover the feature. This includes test coverage to make sure that the previous workflow still works, if applicable.
- [x]   Do manual testing locally. Our tests are not good enough yet to allow us to skip this step. If that’s not applicable for some reason, check this box.
- [ ]   Verify that no Git surgery was necessary, or, if it was necessary at any point, repeat the testing after it’s finished.

- Had to **match migrations** with those in main for dissemination and audit in order to get tests to pass on GH.

- [ ]   Once a PR is merged, keep an eye on it until it’s deployed to dev, and do enough testing on dev to verify that it deployed successfully, the feature works as expected, and the happy path for the broad feature area (such as submission) still works.

## PR checklist: reviewers

- [ ]   Pull the branch to your local environment and run `make docker clean; make docker-first-run && docker compose up`; then run `docker compose exec web /bin/bash -c "python manage.py test"`
- [ ]   Manually test out the changes locally, or check this box to verify that it wasn’t applicable in this case.
- [ ]   Check that the PR has appropriate tests. Look out for changes in HTML/JS/JSON Schema logic that may need to be captured in Python tests even though the logic isn’t in Python.
- [ ]   Verify that no Git surgery is necessary at any point (such as during a merge party), or, if it was, repeat the testing after it’s finished.
        
The larger the PR, the stricter we should be about these points.

### CODE REVIEW

**Review by sambodeme — CHANGES_REQUESTED** [review]
I tested this feature and it mostly works well, but I did notice a couple of issues:

1. When a user selects `USA` and fills out the form, but then switches to a `non-USA` option and re-enters the data, the previous USA-specific inputs are cached and submitted with the form, causing validation to fail and crashes the UI (see screenshot below). The USA-only data should be cleared when users switch from a USA to a non-USA address.
2. When a `non-USA` address is entered,  the fields below come back empty. This makes sense for most fields, except for 'ado.' Should the 'ado' field be empty for non-USA addresses?

**Comment by jperson1** [comment]
I've added a few things:
1. Added a conditional check & wipe for the auditor address in the GeneralInformationFormView.
2. Changed the international address field to a textarea rather than a textarea formatted input field. Now the cursor is top-left rather than center-left.
3. Merged the branch with main to keep it up-to-date for pulling.

**Comment by jperson1** [comment]
@sambodeme 
> When a non-USA address is entered, the fields below come back empty. This makes sense for most fields, except for audit_period_other_months Should the audit_period_other_months field be empty for non-USA addresses?

`audit_period_other_months` should be empty if its field above the Auditee information is empty (or unselected). I think they're showing up next to each other because they are adjacent alphabetically? It's not related to the address fields. 

This one:
image

**Comment by sambodeme** [comment]
@jperson1 I'll give it a try tomorrow. I noticed that when I toggle between the USA and non-USA settings, the `audit_period_other_months` field changes from non-empty to empty. I had `Audit Period`  set to "Annual" and I didn't alter that setting while switching between USA and non-USA.

**Review by sambodeme — APPROVED** [review]
Re-tested and LGTM

**Pull request merged**
