### PR TITLE
Add djlint to dev env

### PR DESCRIPTION
**Pull request by JeanMarie-TTS**
Added djlint to requirements.in and made the necessary changes in Makefile and the development documentation.
Formatted one directory (audit/templates) to make sure reformatting works and does not break anything.

Pending Tasks:

1.  Reformat all template files.
2. Resolve linting issues
3. Add djlint to GH workflow 

The above tasks have now been completed.

### CODE REVIEW

**Review by heymatthenry — DISMISSED** [review]
Were the whitespace changes in My Submissions due to running `djlint`? It would be good to let `djlint` format all of the existing templates in this PR so we can have consistent whitespace going forward without having to introduce noisy formatting commits on unrelated tickets.

I'm ignoring the Black CI error since I'm assuming it's unrelated to this but we should also figure that out before merging just in case.

JM: Both of these are resolved.

**Comment by LindsayYoung** [comment]
I don't this to the the github workflow

**Comment by JeanMarie-TTS** [comment]
@heymatthenry , I tried resolving the linting issues identified by djlint. Avoided some by ignoring them with the relevant updates to pyproject.html. Please see if these should be addressed or ignored.

I need @jasnakai or you to help fix one file where the issues are non-trivial:
report_submission/templates/report_submission/step-3.html
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
H025 4:4 Tag seems to be an orphan. <div class="grid-con
H025 5:8 Tag seems to be an orphan. <div class="grid-row
H025 8:16 Tag seems to be an orphan. <fieldset class="usa

If you checkout the branch, you can run `djlint --lint <filename>` . You may have to first run `make compile-dev` and `make install-dev`

**Comment by heymatthenry** [comment]
@JeanMarie-TTS `report_submission/templates/report_submission/step-3.html` should be good to go

**Review by tadhg-ohiggins — APPROVED** [review]

**Pull request merged**
