### PR TITLE
ADR - File uploads

### PR DESCRIPTION
**Pull request by timoballard**
Address #344

### CODE REVIEW

**Review by jasnakai — APPROVED** [review]
LTGM.

**Comment by petermarks-gsa** [comment]
@timoballard Do I understand correctly that the solution you were a part of on the DOJ application made it to production? Do you recall if any of the technology choices needed special consideration for ATO or was it pretty smooth sailing?

**Comment by timoballard** [comment]
@petermarks-gsa Correct, this solution is in production for the DOJ-CRT app and didn't create ATO complications (although to be fair, in the case of DOJ-CRT, the application had already been ATO'd and in production for several months before this feature was added).

This technical stack should be ATO-friendly, as S3 is both FedRAMPed and is offered as a managed service through cloud.gov. ClamAV has been used for similar purposes on a number of other past TTS projects, so if need be we can reach out to colleagues involved in that work to learn from their ATO experiences in this area.

**Review by petermarks-gsa — APPROVED** [review]
@timoballard Thanks for context. Adding my ✅

**Review by jasnakai — APPROVED** [review]
Added frontend considerations.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Are we good to merge and call this approved?

**Review by tadhg-ohiggins — APPROVED** [review]

**Pull request merged**
