### PR TITLE
Ez/e2e upload tests

### PR DESCRIPTION
**Pull request by eazapata23**
This PR covers e2e tests for xlsx upload #928 (SF-SAC uploads) and should resolve issue #1055. 

Things I've done: 
1) file-upload test suite that include both happy/sad paths for xl uploads
2) each upload page has their own individual e2e test for happy/sad path
3) added success-response.json & fail-response.json and excel templates in fixtures
4) Using 'cy.intercept()' to stub network requests
5) added and installed cypress-file-upload

Examples: 

https://user-images.githubusercontent.com/99770283/236542308-1e7c0f0c-9b23-4879-aa5b-1be694095b52.mov

### CODE REVIEW

**Review by heymatthenry — APPROVED** [review]
One (non-blocking) suggestion. Unless there's a good reason it's there, ideally I'd prefer not to commit commented-out code. Otherwise LGTM!

**Comment by eazapata23** [comment]
> One (non-blocking) suggestion. Unless there's a good reason it's there, ideally I'd prefer not to commit commented-out code. Otherwise LGTM!

My mistake, thank you for pointing that out I did end up getting rid of them.

**Review by jperson1 — APPROVED** [review]
Yay! I do see a few comments that may not need to exist, in `audit-findings-text.cy.js` and `audit-findings.cy.js`.

**Comment by jadudm** [comment]
@eazapata23 , I wonder if by merging in @jperson1 's error handling pieces we now have a merge conflict? Apologies. I was working down the list. If you could take a look, and I'll merge this in so it's in `main`. Apologies for the delay.

**Comment by eazapata23** [comment]
> @eazapata23 , I wonder if by merging in @jperson1 's error handling pieces we now have a merge conflict? Apologies. I was working down the list. If you could take a look, and I'll merge this in so it's in `main`. Apologies for the delay.

No worries, I'll take a look!

**Pull request merged**
