### PR TITLE
Use tasklists in issue templates

### PR DESCRIPTION
**Pull request by mogul**
We want to encourage the use of task lists from the time that story issues are created so that it's easy to break ACs and tasks out into sub-issues as needed without losing hierarchy.

(Note the preview of these changes won't properly render the tasklist in the PR context, but I verified the markup in an existing issue to ensure it's correct.)

### CODE REVIEW

**Comment by jadudm** [comment]
Unfortunately, the iterations we did on the story ticket moved past this PR, but the custom.md changes still make sense. Thoughts?

**Comment by mogul** [comment]
I dropped the commit that modified the story template, rebased on main, and did a force push to this branch to limit it to just the non-story-template changes.

**Comment by jadudm** [comment]
LGTM. Thank you.

**Review by jadudm — APPROVED** [review]
We did the iteration on the story template in another PR. LGTM.

**Pull request merged**
