### PR TITLE
2867 update logic in findings text generator to use census models

### PR DESCRIPTION
**Pull request by sambodeme**
## Description
Updated the findings text workbook generator logic to use Census models from `models.py`, replacing the previously used custom models from `census.py`. This involved:

- Modifying references to field names to align with the Census models.
- Reorganizing and refactoring parts of the logic to enhance reusability.
- Transitioning from custom queries to standard Django ORM query styles.

## How to Test:

1. Start with a clean environment:

        - Run make docker-clean
        - Followed by make docker-first-run
        - Then execute docker compose up

2. Execute the steps described in the [how-to-load-test-census-into-postgres](https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/README.md#how-to-load-test-census-data-into-postgres) of the README.
3. At this point, you can opt to test either the [historic workbook generator](https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/README.md#how-to-run-the-historic-workbook-generator) or the [historic data migrator](https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/README.md#how-to-run-the-historic-data-migrator). To perform these tests:

      - Use any dbkey found in the first part of the subfolder names located in `census_historical_migration/fixtures/workbooks/should_pass`. The subfolders are named using the pattern `dbkey-year`.
 
## PR checklist: submitters

- [ ]   Link to an issue if possible. If there’s no issue, describe what your branch does. Even if there is an issue, a brief description in the PR is still useful.
- [ ]   List any special steps reviewers have to follow to test the PR. For example, adding a local environment variable, creating a local test file, etc.
- [ ]   For extra credit, submit a screen recording like [this one](https://github.com/GSA-TTS/FAC/pull/1821).
- [ ]   Make sure you’ve merged `main` into your branch shortly before creating the PR. (You should also be merging `main` into your branch regularly during development.)
- [ ]   Make sure you’ve accounted for any migrations. When you’re about to create the PR, bring up the application locally and then run `git status | grep migrations`. If there are any results, you probably need to add them to the branch for the PR. Your PR should have only **one** new migration file for each of the component apps, except in rare circumstances; you may need to delete some and re-run `python manage.py makemigrations` to reduce the number to one. (Also, unless in exceptional circumstances, your PR should not delete any migration files.)
- [ ]   Make sure that whatever feature you’re adding has tests that cover the feature. This includes test coverage to make sure that the previous workflow still works, if applicable.
- [ ]   Make sure the full-submission.cy.js [Cypress test](https://github.com/GSA-TTS/FAC/blob/main/docs/testing.md#end-to-end-testing) passes, if applicable.
- [ ]   Do manual testing locally. Our tests are not good enough yet to allow us to skip this step. If that’s not applicable for some reason, check this box.
- [ ]   Verify that no Git surgery was necessary, or, if it was necessary at any point, repeat the testing after it’s finished.
- [ ]   Once a PR is merged, keep an eye on it until it’s deployed to dev, and do enough testing on dev to verify that it deployed successfully, the feature works as expected, and the happy path for the broad feature area (such as submission) still works.

## PR checklist: reviewers

- [ ]   Pull the branch to your local environment and run `make docker-clean; make docker-first-run && docker compose up`; then run `docker compose exec web /bin/bash -c "python manage.py test"`
- [ ]   Manually test out the changes locally, or check this box to verify that it wasn’t applicable in this case.
- [ ]   Check that the PR has appropriate tests. Look out for changes in HTML/JS/JSON Schema logic that may need to be captured in Python tests even though the logic isn’t in Python.
- [ ]   Verify that no Git surgery is necessary at any point (such as during a merge party), or, if it was, repeat the testing after it’s finished.

The larger the PR, the stricter we should be about these points.

### CODE REVIEW

**Review by JeanMarie-TTS — CHANGES_REQUESTED** [review]
Let's use django ORM.
Let's use relative imports within the same app.

**Comment by sambodeme** [comment]
> Let's use django ORM. Let's use relative imports within the same app.

@JeanMarie-TTS please review the PR again. There are multiple PRs open, with each one targeting a specific aspect of the code. In each PR, custom queries related to the relevant code section are being replaced with ORM. By the end [of this task list,](https://github.com/GSA-TTS/FAC/issues/2854) all custom queries will have been substituted by ORM, eliminating any custom queries.

Regarding the use of relative imports, this issue has already been [ticketed](https://github.com/GSA-TTS/FAC/issues/2890) and will be addressed across the entire app. This pattern is used across the entire application; for example, see here in [the audit app](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/cross_validation/sac_validation_shape.py#L1). Dan and I discussed this yesterday, and he suggested implementing linting or a policy at the application level to systematically address this (which will also help to prevent this in the future).

**Comment by JeanMarie-TTS** [comment]
> > Let's use django ORM. Let's use relative imports within the same app.
> 
> @JeanMarie-TTS please review the PR again. There are multiple PRs open, with each one targeting a specific aspect of the code. In each PR, custom queries related to the relevant code section are being replaced with ORM. By the end [of this task list,](https://github.com/GSA-TTS/FAC/issues/2854) all custom queries will have been substituted by ORM, eliminating any custom queries.
> 
> Regarding the use of relative imports, this issue has already been [ticketed](https://github.com/GSA-TTS/FAC/issues/2890) and will be addressed across the entire app. This pattern is used across the entire application; for example, see here in [the audit app](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/cross_validation/sac_validation_shape.py#L1). Dan and I discussed this yesterday, and he suggested implementing [linting policy](https://github.com/GSA-TTS/FAC/pull/2863#pullrequestreview-1751653932) at the application level to systematically address this (which will also help to prevent this in the future).

Let's go ahead and merge this PR now. I'd prefer tp see small refactoring changes included when we see then rather than queue them up for later. Complex ones are the ones that should be tracked in separate tickets.

**Review by JeanMarie-TTS — APPROVED** [review]
Requested changes will be implemented in a different PR

**Pull request merged**
