### PR TITLE
2023-06-26 main -> prod

### PR DESCRIPTION
**Pull request by tadhg-ohiggins**
Uploads on `staging`—
At least I really hope so.
One way to find out…

-----

We're using staging for our user tests, so we need to push the version with working uploads from `dev` to `staging`.

This also has some Docker build changes unrelated to the upload work, which I am unable to evaluate because their names use title case instead of sentence case.

### CODE REVIEW

**Comment by tadhg-ohiggins** [comment]
I marked this as draft because I don't get why we're seeing a merge conflict.

**Comment by asteel-gsa** [comment]
@tadhg-ohiggins i think your merge conflict is here:

main
```bash
S3_ENDPOINT_FOR_NO_PROXY="$(echo $VCAP_SERVICES | jq --raw-output --arg service_name "fac-public-s3" ".[][] | select(.name == \$service_name) | .credentials.endpoint")"
S3_FIPS_ENDPOINT_FOR_NO_PROXY="$(echo $VCAP_SERVICES | jq --raw-output --arg service_name "fac-public-s3" ".[][] | select(.name == \$service_name) | .credentials.fips_endpoint")"
S3_PRIVATE_ENDPOINT_FOR_NO_PROXY="$(echo $VCAP_SERVICES | jq --raw-output --arg service_name "fac-private-s3" ".[][] | select(.name == \$service_name) | .credentials.endpoint")"
S3_PRIVATE_FIPS_ENDPOINT_FOR_NO_PROXY="$(echo $VCAP_SERVICES | jq --raw-output --arg service_name "fac-private-s3" ".[][] | select(.name == \$service_name) | .credentials.fips_endpoint")"
export no_proxy="${S3_ENDPOINT_FOR_NO_PROXY},${S3_FIPS_ENDPOINT_FOR_NO_PROXY},${S3_PRIVATE_ENDPOINT_FOR_NO_PROXY},${S3_PRIVATE_FIPS_ENDPOINT_FOR_NO_PROXY},apps.internal"
```

prod
```bash
S3_ENDPOINT_FOR_NO_PROXY="$(echo $VCAP_SERVICES | jq --raw-output --arg service_name "fac-public-s3" ".[][] | select(.name == \$service_name) | .credentials.endpoint")"
S3_FIPS_ENDPOINT_FOR_NO_PROXY="$(echo $VCAP_SERVICES | jq --raw-output --arg service_name "fac-public-s3" ".[][] | select(.name == \$service_name) | .credentials.fips_endpoint")"
export no_proxy="${S3_ENDPOINT_FOR_NO_PROXY},${S3_FIPS_ENDPOINT_FOR_NO_PROXY},apps.internal"
```

Might be the same thing that happened last time with the comment in `settings.py`

just out of curiosity, im going to close this really quick, and open #1337 which was done earlier. It will not include [82cf2c5](https://github.com/GSA-TTS/FAC/pull/1340/commits/82cf2c53044b9d05d7760d3ac29902a20eb8defc) or [8bd3636](https://github.com/GSA-TTS/FAC/pull/1340/commits/8bd36367a52a6e182cebf8535bcc8268885a1ff4) but im just confirming the conflict is happening in those 2 commits

**Comment by asteel-gsa** [comment]
Still a conflict.

**Comment by tadhg-ohiggins** [comment]
Current hypothesis: https://github.com/GSA-TTS/FAC/commit/1dac0c7efb6c4b494ae7dbc7a989faee17203a93 was squash-merged, and this caused the history problems resulting in the phantom merge conflict Github is seeing. This is likely what happened last time as well.

To fix it, we need to:

1.  Check `prod` out locally.
2.  Roll that local version back to a prior commit (Alex identified `67e651743e6d5c2a0abd97442499ff8f927c8809` as the likely target).
3.  Force-push that to the repository `prod`.
4.  Take this PR out of draft as it will hopefully apply cleanly at that point (or create a new PR if that doesn’t work for some reason).

I’ve added two related items to the dev huddle agenda, about removing squash merge capabilities from the repository entirely and about fully automating the daily automated merges.

**Review by asteel-gsa — APPROVED** [review]

**Pull request merged**
