### PR TITLE
Bug: Handle International Auditor Addresses

### PR DESCRIPTION
**Pull request by jperson1**
# Handle International Auditor Addresses

ZD: https://fac-gov.zendesk.com/agent/tickets/2639

## Changes:
1. Schemas:
    * Always require auditor address fields
    * All auditor address fields are allowed to be blank
    * Determine form complete-ness based on whether the auditor is USA-based and the content of the relevant fields.
2. Reformat search summary to use the international address if the domestic address doesn't exist. 

## How to test:
1. Switch to the main branch. Verify that using an international auditor address causes an issue at validation. 
2. Switch to this branch. Verify that the issue does no occur.
3. Attempt a few different address inputs and verify that things step forward correctly. 
    * Incomplete address info of any kind should result in the General Information section of the checklist appearing incomplete. 
    * Regular addresses should still work just fine. 
    * Saving a USA address then coming back and switching to a non-USA address should wipe the previous fields. The same applies the other way.
4. Step through to dissemination. Verify that it passes IntakeToDissemination.
5. Verify that the newly submitted audit displays the international address in search. 

## Screenshots:
International address:
image

General information section appears complete:
image

No General Information errors at validation:
image

Completing all the other sections still disseminates the audit:
image

International addresses display in search:
image

## PR checklist: submitters

- [ ]   Link to an issue if possible. If there’s no issue, describe what your branch does. Even if there is an issue, a brief description in the PR is still useful.
- [x]   List any special steps reviewers have to follow to test the PR. For example, adding a local environment variable, creating a local test file, etc.
- [ ]   For extra credit, submit a screen recording like [this one](https://github.com/GSA-TTS/FAC/pull/1821).
- [x]   Make sure you’ve merged `main` into your branch shortly before creating the PR. (You should also be merging `main` into your branch regularly during development.)
- [x]   Make sure you’ve accounted for any migrations. When you’re about to create the PR, bring up the application locally and then run `git status | grep migrations`. If there are any results, you probably need to add them to the branch for the PR. Your PR should have only **one** new migration file for each of the component apps, except in rare circumstances; you may need to delete some and re-run `python manage.py makemigrations` to reduce the number to one. (Also, unless in exceptional circumstances, your PR should not delete any migration files.)
- [ ]   Make sure that whatever feature you’re adding has tests that cover the feature. This includes test coverage to make sure that the previous workflow still works, if applicable.
- [x]   Make sure the full-submission.cy.js [Cypress test](https://github.com/GSA-TTS/FAC/blob/main/docs/testing.md#end-to-end-testing) passes, if applicable.
- [x]   Do manual testing locally. Our tests are not good enough yet to allow us to skip this step. If that’s not applicable for some reason, check this box.
- [x]   Verify that no Git surgery was necessary, or, if it was necessary at any point, repeat the testing after it’s finished.
- [ ]   Once a PR is merged, keep an eye on it until it’s deployed to dev, and do enough testing on dev to verify that it deployed successfully, the feature works as expected, and the happy path for the broad feature area (such as submission) still works.

## PR checklist: reviewers

- [ ]   Pull the branch to your local environment and run `make docker-clean; make docker-first-run && docker compose up`; then run `docker compose exec web /bin/bash -c "python manage.py test"`
- [ ]   Manually test out the changes locally, or check this box to verify that it wasn’t applicable in this case.
- [ ]   Check that the PR has appropriate tests. Look out for changes in HTML/JS/JSON Schema logic that may need to be captured in Python tests even though the logic isn’t in Python.
- [ ]   Verify that no Git surgery is necessary at any point (such as during a merge party), or, if it was, repeat the testing after it’s finished.

The larger the PR, the stricter we should be about these points.

### CODE REVIEW

**Review by phildominguez-gsa — APPROVED** [review]
Works nicely!

**Comment by jperson1** [comment]
This functionality has been moved to a new branch for PR https://github.com/GSA-TTS/FAC/pull/3534, so it can instead be merged with @sambodeme's earlier General Information schema/validation changes.

**Comment by James-Paul-Mason** [comment]
@jperson1 just wanted to follow up on this issue/ticket: https://fac-gov.zendesk.com/agent/tickets/2639

I can see this PR is being merged with Hassan's earlier PR...does that mean it is going to be live soon? I was concerned that if this issue was merged into another, I would lose track of it. Just wondering the best way to track the progress of the fix and reply to the user. I should be able to interpret the GH tickets better. Maybe someone can give me a brief tutorial!

**Comment by jperson1** [comment]
@James-Paul-Mason 

To avoid future code conflicts, the changes I made here are going to go first into Hassan's branch and then into main. I expected this one to be quick, so there's no related GitHub issue to point at and say, "This thing is done!"

I made one real quick, https://github.com/GSA-TTS/FAC/issues/3538. You can track the ticket from there, and I'll do my best to keep it updated as we go along. 

Issues and PRs are a "same but different" kind of thing. They're both under the same numbering system, and appear somewhat similarly. Both can be opened and closed, assigned to individuals, and given appropriate labels. The big difference is that an issue is tracks work being done, and a PR is a request to merge specific code together. So, issues are higher level and are better used to track when, "The thing is done!" 

Happy to answer more questions or run through things on Slack or in a meet!

**Pull request closed without merging**
