### PR TITLE
Implement SMTP egress proxy

### PR DESCRIPTION
**Pull request by mogul**
Relates to #1071.

### CODE REVIEW

**Comment by JeanMarie-TTS** [comment]
It would be good to add some test scripts to show that we can send emails via the GSA SMTP service  and that we cannot do so via some other SMTP service provider.

**Comment by jadudm** [comment]
Does "it would be good to..." mean:

1. I think someone/the ticket originator should do this as part of this ticket/PR,
2. I think we should ticket it separately, OR
3. I think this is a good idea, and I'll do it?

**Comment by JeanMarie-TTS** [comment]
"It would be good" means this is a recommendation to the PR owner. They can choose to implement as part of the PR, say this does not make sense and why, create a ticket for later implementation, etc.

**Comment by mogul** [comment]
> It would be good to add some test scripts to show that we can send emails via the GSA SMTP service and that we cannot do so via some other SMTP service provider.

Unlike the `https-proxy`, the `stream-proxy` only ever passes bytes between the client and [the specific preconfigured upstream host+port](https://github.com/GSA-TTS/FAC/pull/1156/files#diff-4fc62bb315d8ddecd4d3a66f85038573ad8c2fa3811467c8c8072b1ffc87c7c3R20) (the "stream")... There's no logic to filter requests based on a requested destination, because the client can't even specify a destination! 

So it wouldn't make sense to add a test specifically for the GSA SMTP service.

**Comment by mogul** [comment]
Let me know if y'all want a walkthrough of this before approving/merging!

**Comment by asteel-gsa** [comment]
> Let me know if y'all want a walkthrough of this before approving/merging!

Happy to do a walkthrough if you have time in the next hour, and can approve.

**Comment by JeanMarie-TTS** [comment]
LGTM - Will leave the approval to Alex after the walkthrough.

**Comment by JeanMarie-TTS** [comment]
> > It would be good to add some test scripts to show that we can send emails via the GSA SMTP service and that we cannot do so via some other SMTP service provider.
> 
> Unlike the `https-proxy`, the `stream-proxy` only ever passes bytes between the client and [the specific preconfigured upstream host+port](https://github.com/GSA-TTS/FAC/pull/1156/files#diff-4fc62bb315d8ddecd4d3a66f85038573ad8c2fa3811467c8c8072b1ffc87c7c3R20) (the "stream")... There's no logic to filter requests based on a requested destination, because the client can't even specify a destination!
> 
> So it wouldn't make sense to add a test specifically for the GSA SMTP service.

Good for now. But I think we should create a test to send an email as a follow yo ticket.. This will give us the confidence that the integration is working. We should not be having paths with no test coverage.

**Review by asteel-gsa — APPROVED** [review]

**Comment by mogul** [comment]
Note from walkthrough with Alex: I'm going to add a Mermaid diagram showing how the test works, since it's not obvious that the client app is acting both as a client and as the proxy's upstream. (Essentially, the client app is a mock.)

**Comment by mogul** [comment]
> > So it wouldn't make sense to add a test specifically for the GSA SMTP service.
> 
> Good for now. But I think we should create a test to send an email as a follow yo ticket.. This will give us the confidence that the integration is working. We should not be having paths with no test coverage.

If you want to be able to prove that the _application_ sends mails, and that they will be delivered to the right location when they're submitted to the G Suite SMTP Relay, that's pretty out of scope for what the proxy actually does... The sole function of the proxy is to enable controlling/funneling egress traffic. 

What you're describing is more of an integration test. I was originally going to do that with mailhog as the mock, but once I started working on it I realized that I was testing a lot more than what the module actually does. I do think there's a call for mailhog to be integrated into the `docker-compose` stack with tests there for the application sending mails as expected, but that's a whole `COULD` issue.

**Comment by mogul** [comment]
(I invite you to contemplate what kind of controlled test setup would be necessary to send a mail through the G Suite SMTP Relay _and_ verify that it was delivered, even without the proxy in the loop. 😜)

**Comment by mogul** [comment]
> I'm going to add a Mermaid diagram showing how the test works, since it's not obvious that the client app is acting both as a client and as the proxy's upstream. (Essentially, the client app is a mock.)

[I added that diagram.](https://github.com/GSA-TTS/FAC/pull/1156/files?short_path=4f09979#diff-4f099791113d6c4fb834e76b77963083079a5f276e5ca43f0047bd7f41490dfe) I also reordered the commits to make them easier to follow in sequence.

**Pull request merged**
