### PR TITLE
Jm/refactor presac

### PR DESCRIPTION
**Pull request by JeanMarie-TTS**
1. Combined URL pathe for each step into a single path with the ste step # as a a query parameter. Combined the views as well.
2. Refactored the html docs by extracting common elements into base_step.html

### CODE REVIEW

**Review by geekygirlsarah — APPROVED** [review]
I think this is helpful. I have a couple of questions about things, but since it's getting merged into feature branch that's still in progress, I'm happy to just merge it and look at them there.

I'd like @jasnakai 's eyes before merging.

**Review by jasnakai — APPROVED** [review]
LGTM!

**Comment by jasnakai** [comment]
I agree with Sarah's above comment. I am going to review this with Matt as he is the lead frontend dev. I will bring up any questions/comments then. Thx!

**Comment by geekygirlsarah** [comment]
> I am going to review this with Matt as he is the lead frontend dev. I will bring up any questions/comments then.

So should I merge or not @jasnakai ?

**Comment by jasnakai** [comment]
Yes. Merge away!

**Pull request merged**
