### PR TITLE
Fixed xlsx copy paste drag down error

### PR DESCRIPTION
**Pull request by sambodeme**
## Description
- Fixed xlsx copy-paste/drag-down error
- Updated xlsx templates

### CODE REVIEW

**Comment by timoballard** [comment]
We can discuss during cowork, but I _suspect_ that this should be targetting the `jadudm/xlsx-gen-spike` branch instead of `main`

**Comment by jperson1** [comment]
> We can discuss during cowork, but I _suspect_ that this should be targetting the `jadudm/xlsx-gen-spike` branch instead of `main`

Agreed - this looks like a superset of PR https://github.com/GSA-TTS/FAC/pull/1120

**Comment by sambodeme** [comment]
> We can discuss during cowork, but I _suspect_ that this should be targetting the `jadudm/xlsx-gen-spike` branch instead of `main`

I created this branch from jadudm/xlsx-gen-spike. The PR for jadudm/xlsx-gen-spike was out and I was expecting it to get merged quickly but I did not get feedback for few days and I needed to add other changes that require jadudm/xlsx-gen-spike, so I started to work on a separate that include the changes in jadudm/xlsx-gen-spike. The expectation here is that jadudm/xlsx-gen-spike gets merged first. This PR will have no issue merging then.

**Comment by timoballard** [comment]
> > We can discuss during cowork, but I _suspect_ that this should be targetting the `jadudm/xlsx-gen-spike` branch instead of `main`
> 
> I created this branch from jadudm/xlsx-gen-spike. The PR for jadudm/xlsx-gen-spike was out and I was expecting it to get merged quickly but I did not get feedback for few days and I needed to add other changes that require jadudm/xlsx-gen-spike, so I started to work on a separate that include the changes in jadudm/xlsx-gen-spike. The expectation here is that jadudm/xlsx-gen-spike gets merged first. This PR will have no issue merging then.

Yep, understood and makes sense - for clarity I would suggest that while #1120 remains open, this one can be marked as a draft and/or target the `jadudm/xlsx-gen-spike` so that it's easier to see the specific changes that this PR is making in the meantime. Then once #1120 gets merged, this one could be updated to target `main`. Does that make sense?

**Pull request closed without merging**
